### ISSUE TITLE
COVID19_Fallzahlen_Kanton_GL_total.csv uses different column names compared to rest

### ISSUE THREAD

**Issue by weentermute** [zdavatz/covid19_ch#12]
See https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_GL_total.csv

**Comment by zdavatz** [comment]
Thanks! I will open an issue!

**Comment by zdavatz** [comment]
@weentermute Can you please post the correct vs the wrong header here:

**Comment by weentermute** [comment]
Correct: 
```
date,time,abbreviation_canton_and_fl,ncumul_tested,ncumul_conf,ncumul_hosp,ncumul_ICU,ncumul_vent,ncumul_released,ncumul_deceased,source
```
Wrong:
```
date,time,abbreviation_canton,ncumul_tested,ncumul_conf,ncumul_hosp,ncumul_ICU,ncumul_vent,ncumul_released,ncumul_deceased,source
```
Looks like only `abbreviation_canton` is wrong. Should be `abbreviation_canton_and_fl`.

**Comment by zdavatz** [comment]
Great thank you! I will try to send them a Pull-Request.

Can you please create a report file, every time you run your script, see: https://github.com/zdavatz/covid19_ch/issues/11 

@cybermax know what I mean. He done lots of that for [aips2sqlite](https://github.com/zdavatz/aips2sqlite) ;)

**Comment by zdavatz** [comment]
@weentermute PR sent: https://github.com/openZH/covid_19/pull/54

**Comment by zdavatz** [comment]
Done. Please test the new file.
