### ISSUE TITLE
Source Issue Canton Aargau

### ISSUE THREAD

**Issue by tombenzeen** [zdavatz/covid19_ch#23]
referenced source from AG is outdated. 
new buletin is with following link:
https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200330_KFS_Coronavirus_Lagebulletin_22.pdf

overview of all buletins here:
https://www.ag.ch/de/themen_1/coronavirus_2/lagebulletins/lagebulletins_1.jsp

probalby check first the newest bulelletins link...

**Comment by zdavatz** [comment]
Thank you! Can you please be more precise what your issue is.

**Comment by cybermax** [comment]
Thank you very much. There is a delay between the time the bulletin is released, our scraping activity and when our database is compiled. It's up-to-date now. Please have a look.
