### ISSUE TITLE
Data not anymore available

### ISSUE THREAD

**Issue by tgdbepe4** [zdavatz/covid19_ch#33]
Hi Zeno

I consume the follow data file from your site for my excel dashboard:

https://raw.githubusercontent.com/zdavatz/covid19_ch/master/data-switzerland-csv/dd-covid19-openzh-switzerland-latest.csv
https://raw.githubusercontent.com/openZH/covid_19/master/COVID19_Fallzahlen_CH_total.csv
https://raw.githubusercontent.com/zdavatz/covid19_ch/master/data-cantons-csv/dd-covid19-openzh-cantons-latest.csv

These data are not anymore available. What is the reason for that?

Kind regards

Peter

**Comment by zdavatz** [comment]
sorry, but above links work.

**Comment by tgdbepe4** [comment]
Hi Zeno

Not does not work. Also in Browser:

This pop up in Firefox:
![grafik](https://user-images.githubusercontent.com/46052442/85746426-bdc96280-b706-11ea-9141-b0fede9581d4.png)

Any idea?

**Comment by zdavatz** [comment]
keine Ahnung was Du machst. Versuch mal mit wget.
