### ISSUE TITLE
Ongoing discussion about Data formats

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/covid19_ch#7]
https://forum.opendata.ch/t/epidemic-curves/627/6, initiated by https://www.linkedin.com/in/francesca-de-chiara-30342437/

**Comment by tgdbepe4** [comment]
Bitte das Datenfile um die Kantonsnummer "KANTONNUM" ergänzen, wie das im Kantonsshapefile vom BFS der Fall ist.

![grafik](https://user-images.githubusercontent.com/46052442/77221402-bc0d6300-6b49-11ea-8f42-d1b5c885f557.png)

**Comment by zdavatz** [comment]
@tgdbepe4 hast Du ein gesamtes File mit allen Kantonsnummer? Dann pflegen wir das ein. @cybermax FYI.

**Comment by zdavatz** [comment]
woher kommt dieser Screenshot?

**Comment by tgdbepe4** [comment]
Aus QGIS Attribute-Tabelle des Shapefile vom BFS. Hänge dies als zip heir an.

Im Shapefile "Mittelpunkt von Kantonen" habe ich die Kantonsdaten so reduziert, dass diese nur einmal vorhanden sind. Die Enklaveninfos habe ich herausgelöscht.

[corona.ch.zip](https://github.com/zdavatz/covid19_ch/files/4362747/corona.ch.zip)

**Comment by zdavatz** [comment]
Danke! @tgdbepe4 hast Du Erfahrung mit github? Kannst Du uns einen Pull-Request senden?

**Comment by tgdbepe4** [comment]
Ja etwas. Ich denke es wäre gut, wenn du mich kurz anrufst.

**Comment by zdavatz** [comment]
done with: 4e4bad8093ec622eb037b9666087c8438ad354e8
