### ISSUE TITLE
BAG Fax formular

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/covid19_ch#8]
[BAG Fax Formular for Covid19 Fälle](https://t.co/iYSC9GXxdi?amp=1) und der [Republik](https://www.republik.ch/2020/03/20/die-zahl-der-todesfaelle-haben-wir-aus-wikipedia-entnommen) Artikel dazu.

**Comment by tgdbepe4** [comment]
Dies ist recht störend aber eine rein digitale Lösung zur Zeit wohl nicht machbar. Deshalb habe ich das reine PDF-File in PDF-Format-File umgebaut. Leider fand ich keinen Weg, um dies dem BAG zu posten. Aber ein paar Ärzte sind froh darüber!

[ncov2019_d-edit_202003191639.pdf](https://github.com/zdavatz/covid19_ch/files/4362531/ncov2019_d-edit_202003191639.pdf)

**Comment by zdavatz** [comment]
@tgdbepe4 bist Du auf Twitter? Poste es auf Twitter bitte.

**Comment by tgdbepe4** [comment]
Mein Twitter-Account ist @bergis

**Comment by zdavatz** [comment]
sehr gut!

**Comment by tgdbepe4** [comment]
Nun sind die BAG Formulare auf Github, https://github.com/tgdbepe4/corona_ch_bag_formulare

**Comment by zdavatz** [comment]
@tgdbepe4 super, Danke!
